### ISSUE TITLE
Compatibility with version WC 2.4

### ISSUE THREAD

**Issue by danider96** [artprojectgroup/wc-apg-nifcifnie-field#1]
Tengo un WordPress con Woocoommerce 4.4 y al recibir el token de retorno de redsys o consultar la lista de pedidos recibo este error:

`[Tue Aug 22 09:56:57.855109 2023] [proxy_fcgi:error] [pid 2229797:tid 140191993935616] [client 195.76.9.187:10400] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Error: Call to undefined method WC_Order::get_shipping_phone() in /path/to/wp/wordpress/wp-content/plugins/wc-apg-nifcifnie-field/includes/clases/direcciones.php:32\nStack trace:\n#0 /path/to/wp/wordpress/wp-includes/class-wp-hook.php(307): APG_Campo_NIF_en_Direcciones->apg_nif_formato_direccion_envio_pedido()\n#1 /path/to/wp/wordpress/wp-includes/plugin.php(189): WP_Hook->apply_filters()\n#2 /path/to/wp/wordpress/wp-content/plugins/woocommerce/includes/class-wc-order.php(931): apply_filters()\n#3 /path/to/wp/wordpress/wp-content/plugins/woocommerce/templates/emails/plain/email-addresses.php(32): WC_Order->get_formatted_shipping_address()\n#4 /path/to/wp/wordpress/wp-content/plugins/woocommerce/includes/wc-core-functions.php(344): include('/path/to/wp...')\n#5 /path/to/wp/wordpress/...'`

El plugin dice que el requisito tiene woocommerce 2.4.0, pero se llama un hook que no se introdujo hasta la versión 5.6.0 https:///woocommerce.github.io/code-reference/classes/WC-Order.html#method_get_shipping_phone Espero que pueda ayudarme gracias

**Comment by artprojectgroup** [comment]
Efectivamente tenemos que actualizar la versión mínima compatible ya que la 2.4 hace tiempo que se dejó de ser la mínima.

Ese cambio se realizó en la versión 2.1.0.1 así que si instalas una versión anterior, como la 2.1, debería funcionarte sin problema. El problema es que $pedido->get_meta( '_shipping_phone', true ) ya no es válido en las versiones actuales.

Por cierto deberías actualizar esa versión ya que está más que obsoleta y muy pronto debelará se operarte casi ningún plugin de WooCommerce con la adopción del HPOS.

Un saludo.

**Comment by danider96** [comment]
Muchas gracias por tu rápida respuesta.

Un saludo.
