### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Call to undefined function wc_get_page_id()

### ISSUE THREAD

**Issue by ManuBermudez17** [artprojectgroup/wc-apg-nifcifnie-field#2]
Buenas tardes,
hoy hemos actualizado el plugin a su última versión, y se ha caído toda la web, tanto frontend como backend. 

Nosotros tenemos Wordpress Versión 6.7.1, Woocommerce Versión 9.4.2 y plantilla Woodmart Versión 7.6.0.

Nos ha saltado el siguiente error: 
_

> [22-Nov-2024 12:27:08 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function wc_get_page_id() in /home/customer/www/dominio.com/public_html/wp-content/plugins/wc-apg-nifcifnie-field/includes/admin/funciones-apg.php:100
> Stack trace:
> #0 /home/customer/www/dominio.com/public_html/wp-content/plugins/wc-apg-nifcifnie-field/includes/clases/pedido.php(40): apg_nif_checkout_block()
> #1 /home/customer/www/dominio.com/public_html/wp-content/plugins/wc-apg-nifcifnie-field/includes/clases/pedido.php(710): APG_Campo_NIF_en_Pedido->__construct()
> #2 /home/customer/www/dominio.com/public_html/wp-content/plugins/wc-apg-nifcifnie-field/apg-nif.php(53): include_once('/home/customer/...')
> #3 /home/customer/www/dominio.com/public_html/wp-content/plugins/wc-apg-nifcifnie-field/apg-nif.php(92): APG\WC_APG_nifcifnie_field\APG_Campo_NIF->__construct()
> #4 /home/customer/www/dominio.com/public_html/wp-settings.php(526): include_once('/home/customer/...')
> #5 /home/customer/www/dominio.com/public_html/wp-config.php(84): require_once('/home/customer/...')
> #6 /home/customer/www/dominio.com/public_html/wp-load.php(50): require_once('/home/customer/...')
> #7 /home/customer/www/dominio.com/public_html/wp-blog-header.php(13): require_once('/home/customer/...')
> #8 /home/customer/www/dominio.com/public_html/index.php(17): require('/home/customer/...')
> #9 {main}
>   thrown in /home/customer/www/dominio.com/public_html/wp-content/plugins/wc-apg-nifcifnie-field/includes/admin/funciones-apg.php on line 100
_

Lo he podido solucionar de la siguiente manera: 
Dentro de /wc-apg-nifcifnie-field/includes/admin/funciones-apg.php, la funcion de la linea 100:

He reemplazado: 

> function apg_nif_checkout_block() {
>     return has_block( 'woocommerce/checkout', wc_get_page_id( 'checkout' ) );
> }

Por: 
> function apg_nif_checkout_block() {
>     if ( function_exists( 'wc_get_page_id' ) && function_exists( 'has_block' ) ) {
>         return has_block( 'woocommerce/checkout', wc_get_page_id( 'checkout' ) );
>     }
>     return false; 
> }

No se si será la mejor opción, pero te lo dejo por aquí.

Un saludo!

**Comment by artprojectgroup** [comment]
Muchas gracias por el aviso.

Ya está corregido en la nueva versión.

**Comment by ManuBermudez17** [comment]
He actualizado y a vuelto a fallar:

[22-Nov-2024 13:31:04 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function wc_get_page_id() in /home/customer/www/dominio.com/public_html/wp-content/plugins/wc-apg-nifcifnie-field/includes/clases/pedido.php:40
Stack trace:
#0 /home/customer/www/dominio.com/public_html/wp-content/plugins/wc-apg-nifcifnie-field/includes/clases/pedido.php(710): APG_Campo_NIF_en_Pedido->__construct()
#1 /home/customer/www/dominio.com/public_html/wp-content/plugins/wc-apg-nifcifnie-field/apg-nif.php(53): include_once('/home/customer/...')
#2 /home/customer/www/dominio.com/public_html/wp-content/plugins/wc-apg-nifcifnie-field/apg-nif.php(92): APG\WC_APG_nifcifnie_field\APG_Campo_NIF->__construct()
#3 /home/customer/www/dominio.com/public_html/wp-settings.php(526): include_once('/home/customer/...')
#4 /home/customer/www/dominio.com/public_html/wp-config.php(84): require_once('/home/customer/...')
#5 /home/customer/www/dominio.com/public_html/wp-load.php(50): require_once('/home/customer/...')
#6 /home/customer/www/dominio.com/public_html/wp-blog-header.php(13): require_once('/home/customer/...')
#7 /home/customer/www/dominio.com/public_html/index.php(17): require('/home/customer/...')
#8 {main}
  thrown in /home/customer/www/dominio.com/public_html/wp-content/plugins/wc-apg-nifcifnie-field/includes/clases/pedido.php on line 40

**Comment by artprojectgroup** [comment]
Pues ahí ya no debería fallar y no conseguimos replicar ninguno de los errores reportados.

¿Puedes probar a cambiar esto en apg.php? Línea 92.
        new APG_Campo_NIF();

¿Por esto?
    function apg_nif_carga_plugin() {
        new APG_Campo_NIF();
    }
    add_action( 'woocommerce_loaded', 'action_woocommerce_loaded', 10 ); 

A ver si te corrige el problema

**Comment by artprojectgroup** [comment]
> Pues ahí ya no debería fallar y no conseguimos replicar ninguno de los errores reportados.
> 
> ¿Puedes probar a cambiar esto en apg.php? Línea 92. new APG_Campo_NIF();
> 
> ¿Por esto? function apg_nif_carga_plugin() { new APG_Campo_NIF(); } add_action( 'woocommerce_loaded', 'action_woocommerce_loaded', 10 );
> 
> A ver si te corrige el problema

Déjalo que da error. Dame un momento y te decimos qué hacemos.

**Comment by artprojectgroup** [comment]
Prueba esto:
    add_action( 'woocommerce_loaded', function() {
        new APG_Campo_NIF();        
    } ); 

En lugar de la línea 92 de apg.php:    
         new APG_Campo_NIF();        

A ver si así te funciona.

**Comment by ManuBermudez17** [comment]
> Prueba esto: add_action( 'woocommerce_loaded', function() { new APG_Campo_NIF(); } );
> 
> En lugar de la línea 92 de apg.php: new APG_Campo_NIF();
> 
> A ver si así te funciona.

He realizado estos cambios que me has dicho, y ahora si funciona correctamente. El plugin y el campo carga correctamente. He mirado logs, y no reporta nada sobre este plugin.

**Comment by artprojectgroup** [comment]
Pues nada, actualizamos.

Esto de tener errores que no se pueden replicar en tu entorno de desarrollo, es un problemón :-(

Muchas gracias por el reporte y el testing :-)

Un saludo.

**Comment by ManuBermudez17** [comment]
Me lo imagino, cada proyecto es un mundo y pueden reportar cualquier cosa :)

Gracias a ti por el soporte :)

Un saludo!!
